// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Account
    {
        [DataMember(Name = "Identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "UserName")]
        public string UserName;
        [DataMember(Name = "MailAddress")]
        public string MailAddress;
        [DataMember(Name = "PasswordHash")]
        public string PasswordHash;
        [DataMember(Name = "IsOnline")]
        public bool IsOnline;
        [DataMember(Name = "SendNews")]
        public bool SendNews;
        [DataMember(Name = "AcceptedAGB")]
        public bool AcceptedAgb;
        [DataMember(Name = "NameTokens")]
        public int NameTokens;

        public Account(
            SpacetimeDB.Identity Identity,
            string UserName,
            string MailAddress,
            string PasswordHash,
            bool IsOnline,
            bool SendNews,
            bool AcceptedAgb,
            int NameTokens
        )
        {
            this.Identity = Identity;
            this.UserName = UserName;
            this.MailAddress = MailAddress;
            this.PasswordHash = PasswordHash;
            this.IsOnline = IsOnline;
            this.SendNews = SendNews;
            this.AcceptedAgb = AcceptedAgb;
            this.NameTokens = NameTokens;
        }

        public Account()
        {
            this.UserName = "";
            this.MailAddress = "";
            this.PasswordHash = "";
        }
    }
}
