// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ClientDebugLog
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "Layer")]
        public int Layer;
        [DataMember(Name = "Message")]
        public string Message;
        [DataMember(Name = "CreatedAt")]
        public int CreatedAt;

        public ClientDebugLog(
            SpacetimeDB.Identity Identity,
            int Layer,
            string Message,
            int CreatedAt
        )
        {
            this.Identity = Identity;
            this.Layer = Layer;
            this.Message = Message;
            this.CreatedAt = CreatedAt;
        }

        public ClientDebugLog()
        {
            this.Message = "";
        }
    }
}
