// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ClientToken
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "Tkn")]
        public string Tkn;

        public ClientToken(
            SpacetimeDB.Identity Identity,
            string Tkn
        )
        {
            this.Identity = Identity;
            this.Tkn = Tkn;
        }

        public ClientToken()
        {
            this.Tkn = "";
        }
    }
}
