// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PersistentSession
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "Tkn")]
        public string Tkn;
        [DataMember(Name = "CreatedAt")]
        public SpacetimeDB.Timestamp CreatedAt;

        public PersistentSession(
            SpacetimeDB.Identity Identity,
            string Tkn,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.Identity = Identity;
            this.Tkn = Tkn;
            this.CreatedAt = CreatedAt;
        }

        public PersistentSession()
        {
            this.Tkn = "";
        }
    }
}
