// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ChangeSenderUserNameHandler(ReducerEventContext ctx, string userName);
        public event ChangeSenderUserNameHandler? OnChangeSenderUserName;

        public void ChangeSenderUserName(string userName)
        {
            conn.InternalCallReducer(new Reducer.ChangeSenderUserName(userName), this.SetCallReducerFlags.ChangeSenderUserNameFlags);
        }

        public bool InvokeChangeSenderUserName(ReducerEventContext ctx, Reducer.ChangeSenderUserName args)
        {
            if (OnChangeSenderUserName == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnChangeSenderUserName(
                ctx,
                args.UserName
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ChangeSenderUserName : Reducer, IReducerArgs
        {
            [DataMember(Name = "userName")]
            public string UserName;

            public ChangeSenderUserName(string UserName)
            {
                this.UserName = UserName;
            }

            public ChangeSenderUserName()
            {
                this.UserName = "";
            }

            string IReducerArgs.ReducerName => "ChangeSenderUserName";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ChangeSenderUserNameFlags;
        public void ChangeSenderUserName(CallReducerFlags flags) => ChangeSenderUserNameFlags = flags;
    }
}
