// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateAccountHandler(ReducerEventContext ctx, string userName, string mailAddress, string passwordHash, bool sendNews, bool acceptedAgb, string usedToken);
        public event CreateAccountHandler? OnCreateAccount;

        public void CreateAccount(string userName, string mailAddress, string passwordHash, bool sendNews, bool acceptedAgb, string usedToken)
        {
            conn.InternalCallReducer(new Reducer.CreateAccount(userName, mailAddress, passwordHash, sendNews, acceptedAgb, usedToken), this.SetCallReducerFlags.CreateAccountFlags);
        }

        public bool InvokeCreateAccount(ReducerEventContext ctx, Reducer.CreateAccount args)
        {
            if (OnCreateAccount == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateAccount(
                ctx,
                args.UserName,
                args.MailAddress,
                args.PasswordHash,
                args.SendNews,
                args.AcceptedAgb,
                args.UsedToken
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateAccount : Reducer, IReducerArgs
        {
            [DataMember(Name = "userName")]
            public string UserName;
            [DataMember(Name = "mailAddress")]
            public string MailAddress;
            [DataMember(Name = "passwordHash")]
            public string PasswordHash;
            [DataMember(Name = "sendNews")]
            public bool SendNews;
            [DataMember(Name = "acceptedAGB")]
            public bool AcceptedAgb;
            [DataMember(Name = "usedToken")]
            public string UsedToken;

            public CreateAccount(
                string UserName,
                string MailAddress,
                string PasswordHash,
                bool SendNews,
                bool AcceptedAgb,
                string UsedToken
            )
            {
                this.UserName = UserName;
                this.MailAddress = MailAddress;
                this.PasswordHash = PasswordHash;
                this.SendNews = SendNews;
                this.AcceptedAgb = AcceptedAgb;
                this.UsedToken = UsedToken;
            }

            public CreateAccount()
            {
                this.UserName = "";
                this.MailAddress = "";
                this.PasswordHash = "";
                this.UsedToken = "";
            }

            string IReducerArgs.ReducerName => "CreateAccount";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreateAccountFlags;
        public void CreateAccount(CallReducerFlags flags) => CreateAccountFlags = flags;
    }
}
