// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void LoginHandler(ReducerEventContext ctx, string userName, string password);
        public event LoginHandler? OnLogin;

        public void Login(string userName, string password)
        {
            conn.InternalCallReducer(new Reducer.Login(userName, password), this.SetCallReducerFlags.LoginFlags);
        }

        public bool InvokeLogin(ReducerEventContext ctx, Reducer.Login args)
        {
            if (OnLogin == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnLogin(
                ctx,
                args.UserName,
                args.Password
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Login : Reducer, IReducerArgs
        {
            [DataMember(Name = "userName")]
            public string UserName;
            [DataMember(Name = "password")]
            public string Password;

            public Login(
                string UserName,
                string Password
            )
            {
                this.UserName = UserName;
                this.Password = Password;
            }

            public Login()
            {
                this.UserName = "";
                this.Password = "";
            }

            string IReducerArgs.ReducerName => "Login";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags LoginFlags;
        public void Login(CallReducerFlags flags) => LoginFlags = flags;
    }
}
