// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetSenderNewsHandler(ReducerEventContext ctx, bool sendNews);
        public event SetSenderNewsHandler? OnSetSenderNews;

        public void SetSenderNews(bool sendNews)
        {
            conn.InternalCallReducer(new Reducer.SetSenderNews(sendNews), this.SetCallReducerFlags.SetSenderNewsFlags);
        }

        public bool InvokeSetSenderNews(ReducerEventContext ctx, Reducer.SetSenderNews args)
        {
            if (OnSetSenderNews == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetSenderNews(
                ctx,
                args.SendNews
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetSenderNews : Reducer, IReducerArgs
        {
            [DataMember(Name = "sendNews")]
            public bool SendNews;

            public SetSenderNews(bool SendNews)
            {
                this.SendNews = SendNews;
            }

            public SetSenderNews()
            {
            }

            string IReducerArgs.ReducerName => "SetSenderNews";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SetSenderNewsFlags;
        public void SetSenderNews(CallReducerFlags flags) => SetSenderNewsFlags = flags;
    }
}
