// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetSenderOnlineHandler(ReducerEventContext ctx);
        public event SetSenderOnlineHandler? OnSetSenderOnline;

        public void SetSenderOnline()
        {
            conn.InternalCallReducer(new Reducer.SetSenderOnline(), this.SetCallReducerFlags.SetSenderOnlineFlags);
        }

        public bool InvokeSetSenderOnline(ReducerEventContext ctx, Reducer.SetSenderOnline args)
        {
            if (OnSetSenderOnline == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetSenderOnline(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetSenderOnline : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "SetSenderOnline";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SetSenderOnlineFlags;
        public void SetSenderOnline(CallReducerFlags flags) => SetSenderOnlineFlags = flags;
    }
}
