// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetSenderOfflineHandler(ReducerEventContext ctx);
        public event SetSenderOfflineHandler? OnSetSenderOffline;

        public void SetSenderOffline()
        {
            conn.InternalCallReducer(new Reducer.SetSenderOffline(), this.SetCallReducerFlags.SetSenderOfflineFlags);
        }

        public bool InvokeSetSenderOffline(ReducerEventContext ctx, Reducer.SetSenderOffline args)
        {
            if (OnSetSenderOffline == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetSenderOffline(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetSenderOffline : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "SetSenderOffline";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SetSenderOfflineFlags;
        public void SetSenderOffline(CallReducerFlags flags) => SetSenderOfflineFlags = flags;
    }
}
