// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AccountHandle : RemoteTableHandle<EventContext, Account>
        {
            protected override string RemoteTableName => "Account";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Account row) => row.Identity;

                public IdentityUniqueIndex(AccountHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            public sealed class MailAddressUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(Account row) => row.MailAddress;

                public MailAddressUniqueIndex(AccountHandle table) : base(table) { }
            }

            public readonly MailAddressUniqueIndex MailAddress;

            public sealed class UserNameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(Account row) => row.UserName;

                public UserNameUniqueIndex(AccountHandle table) : base(table) { }
            }

            public readonly UserNameUniqueIndex UserName;

            internal AccountHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
                MailAddress = new(this);
                UserName = new(this);
            }

            protected override object GetPrimaryKey(Account row) => row.Identity;
        }

        public readonly AccountHandle Account;
    }
}
