// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ClientDebugLogHandle : RemoteTableHandle<EventContext, ClientDebugLog>
        {
            protected override string RemoteTableName => "ClientDebugLog";

            internal ClientDebugLogHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly ClientDebugLogHandle ClientDebugLog;
    }
}
