// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ClientTokenHandle : RemoteTableHandle<EventContext, ClientToken>
        {
            protected override string RemoteTableName => "ClientToken";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(ClientToken row) => row.Identity;

                public IdentityUniqueIndex(ClientTokenHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal ClientTokenHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(ClientToken row) => row.Identity;
        }

        public readonly ClientTokenHandle ClientToken;
    }
}
