name: Generate and Deploy DocFX

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.115'

    - name: Install Wasi-Wasm Workload
      run: dotnet workload install wasi-experimental

    - name: Install DocFX
      run: dotnet tool install -g docfx

    - name: Install SpacetimeDB
      run: |
        curl -sSf https://install.spacetimedb.com | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Generate spacetime bindings
      run: spacetime generate --lang csharp --out-dir Client_PSL/module_bindings --project-path server --yes

    - name: Build Solution
      run: dotnet build

    - name: Generate DocFX metadata and site
      run: |
        docfx metadata
        docfx build

    - name: Deploy via SCP to Google VM
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.GCP_HOST }}
        username: ${{ secrets.GCP_USER }}
        key: ${{ secrets.GCP_SSH_KEY }}
        source: "_site"
        target: "/var/www/psl-doc"
